# Generated by Django 2.1.5 on 2019-10-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GnuCashCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='GnuCash category name')),
            ],
            options={
                'verbose_name': 'GnuCash category',
                'verbose_name_plural': 'GnuCash categories',
                'ordering': ('name',),
            },
        ),
    ]
