# Generated by Django 4.0.8 on 2022-11-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('double_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gnucashcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
